import Euler.CorrectionTime
import Euler.QuadraticHeatConstraint
import Euler.LiftedTransportComponents

/-! A genuine local divergence-free viscous correction for the transformed Euler equation. -/

noncomputable section

namespace EulerCorrectionOperators

open MeasureTheory InnerProductSpace Set EulerLiftedGradientSpace EulerPressureSpatialRegularity
  EulerSpatialSobolevInverse EulerCylinderSobolev EulerCylinderSobolevSpace EulerSobolevTransport
  EulerSobolevCoefficientPressure EulerQuadraticSource
open scoped Topology

variable (period : ℝ) [Fact (0 < period)]

local instance dataSobolevGroup (q : ℕ) : NormedAddCommGroup (SobolevSpace period q) := inferInstance
local instance dataSobolevSpace (q : ℕ) : NormedSpace ℝ (SobolevSpace period q) := inferInstance

/-- An actual smooth spatial coefficient with its genuine finite Sobolev jet and continuous time action. -/
structure CoefficientPath (q : ℕ) (T : Type*) [TopologicalSpace T] where
  coefficient : T → SmoothCoefficient period
  jet : ∀ t, CoefficientJet period standardDirection q (coefficient t)
  continuous : Continuous (fun t => coefficientSobolevOperator period (jet t))

/-- The path acts by actual pointwise multiplication at each time. -/
def CoefficientPath.operatorPath {q : ℕ} {T : Type*} [TopologicalSpace T]
    (A : CoefficientPath period q T) : C(T, SobolevSpace period q →L[ℝ] SobolevSpace period q) :=
  ⟨fun t => coefficientSobolevOperator period (A.jet t), A.continuous⟩

/-- The concrete coefficient and approximate-solution data of the viscous Euler error equation. -/
structure CorrectionData (q : ℕ) (T : Type*) [TopologicalSpace T] where
  κ : ℝ
  direction : Vector3
  scale_bound : |κ| ≤ 1
  direction_bound : ‖direction‖ ≤ 1
  metric : CoefficientPath period q T
  coercivity : ℝ
  coercivity_pos : 0 < coercivity
  metric_pos : ∀ t x v, coercivity * ‖v‖^2 ≤ ⟪(metric.coefficient t).coefficient x v,v⟫_ℝ
  linear : CoefficientPath period q T
  quadratic : Fin 3 → CoefficientPath period q T
  approximation : C(T, SobolevSpace period (q+1))
  residual : C(T, SobolevSpace period q)

/-- The actual pressure-projected nonlinear correction source generated by the concrete data. -/
def CorrectionData.coefficients {q : ℕ} {T : Type*} [TopologicalSpace T]
    (D : CorrectionData period q T) (hq : 6 ≤ q) :
    Coefficients T (SobolevSpace period (q+1)) (SobolevSpace period q) :=
  correctionCoefficients period hq D.metric.coefficient D.metric.jet D.κ D.direction D.coercivity
    D.coercivity_pos D.metric_pos D.metric.continuous (velocityComponents D.κ D.direction)
    (velocityComponents_norm D.κ D.direction D.scale_bound D.direction_bound)
    D.linear.operatorPath (fun i => (D.quadratic i).operatorPath) D.approximation D.residual

/-- The actual error source is exactly divergence-free; this property is derived from pressure coercivity. -/
theorem CorrectionData.source_gradient_zero {q : ℕ} {T : Type*} [TopologicalSpace T]
    (D : CorrectionData period q T) (hq : 6 ≤ q) (t : T) (u : SobolevSpace period (q+1)) :
    gradientProjection period D.κ D.direction (value period ((D.coefficients period hq).apply t u)) = 0 :=
  correction_source_gradient_zero period hq D.metric.coefficient D.metric.jet D.κ D.direction D.coercivity
    D.coercivity_pos D.metric_pos D.metric.continuous (velocityComponents D.κ D.direction)
    (velocityComponents_norm D.κ D.direction D.scale_bound D.direction_bound)
    D.linear.operatorPath (fun i => (D.quadratic i).operatorPath) D.approximation D.residual t u


end EulerCorrectionOperators
